// This file is auto-generated by scripts/generate-version.mjs
export const APP_VERSION = {
  version: '0.42.0',
  hash: '38525ea',
  branch: 'misc/versioning',
  isDetached: false,
  nodeEnv: 'development',
  buildDate: '2026-05-16T12:56:23.716Z',
  full: 'v0.42.0+38525ea',
} as const;
