// This file is auto-generated by scripts/generate-version.mjs
export const APP_VERSION = {
  version: '0.43.4',
  hash: 'd61de51',
  branch: 'feature/github-actions-harderning',
  isDetached: false,
  nodeEnv: 'development',
  buildDate: '2026-05-17T12:51:46.575Z',
  full: 'v0.43.4+d61de51',
} as const;
