// This file is auto-generated by scripts/generate-version.mjs
export const APP_VERSION = {
  version: '0.43.0',
  hash: '037fd12',
  branch: 'bug/build-updates',
  isDetached: false,
  nodeEnv: 'development',
  buildDate: '2026-05-16T18:23:51.679Z',
  full: 'v0.43.0+037fd12',
} as const;
