export const DAILY_CLARITY_PROMPTS = [
  'A single clear step often feels lighter than many vague ideas.',
  'When thoughts have a place to land, the mind becomes quieter.',
  'Small honest captures create space for what matters most.',
  'Clarity usually begins with writing it down, not figuring it out.',
  'A calm list is often more powerful than a perfect plan.',
  'The gentlest systems are the ones we actually return to.',
  'Progress feels easier when the next action is visible and simple.',
  'Some days, just naming the task is enough.',
  'A quiet inbox is a kind gift to your future self.',
  "The mind works better when it isn't carrying everything at once.",
  'One captured thought can soften the weight of the day.',
  'Simplicity in your system often creates room for creativity.',
  'Trust grows when your tasks feel honest and manageable.',
  'A focused day usually starts with a focused first step.',
  'Letting go of mental loops often begins with writing them down.',
  'The smallest clear action can create surprising momentum.',
  "Order doesn't have to be perfect to be helpful.",
  'A supportive list feels like help, not pressure.',
  'Clarity and calm tend to travel together.',
  'When everything has its place, the mind can rest.',
  'Gentle structure can feel like a deep breath.',
  'What gets captured today stops echoing tomorrow.',
  'A clear surface invites clearer thinking.',
  'The kindest productivity is usually the simplest.',
  'Sometimes the most productive thing is to start.',
  'Peaceful focus starts with a system you trust.',
  'A well-placed task is easier to return to.',
  'Less noise in the mind leaves more room for what matters.',
  'Every small capture is an act of self-kindness.',
  'The clearest days often begin with the clearest intentions.',
  'Done is often better than organized.',
  'One task at a time is still progress.',
  'The next step is usually smaller than it feels.',
  'A list that fits your day beats a list that judges it.',
  "You don't need to clear it all - just begin somewhere.",
];

export const YOTARA_JOURNAL_PROMPTS = [
  '\u201CWithin you, there is a stillness and a sanctuary to which you can retreat at any time.\u201D \u2014 Eckhart Tolle',
  '\u201CA calm mind brings inner strength and self-confidence.\u201D \u2014 Dalai Lama',
  '\u201CPeace of mind comes when you stop trying to control everything.\u201D \u2014 Eckhart Tolle',
  '\u201CYour mind is for having ideas, not holding them.\u201D \u2014 David Allen',
  '\u201CSimplicity is the ultimate sophistication.\u201D \u2014 Leonardo da Vinci',
  '\u201CFocus and simplicity. Simple can be harder than complex.\u201D \u2014 Steve Jobs',
  '\u201CThe clearer the vision, the fewer the options.\u201D \u2014 Andy Stanley',
  '\u201CCalmness is the cradle of power.\u201D \u2014 Josiah Gilbert Holland',
  '\u201CYou must use your mind to get things off your mind.\u201D \u2014 David Allen',
  '\u201CA quiet mind is able to hear intuition over fear.\u201D \u2014 Unknown',
  '\u201CThe present moment is the only time over which we have dominion.\u201D \u2014 Th\u00EDch Nh\u1EA5t H\u1EA1nh',
  '\u201CSimplicity is the keynote of all true elegance.\u201D \u2014 Coco Chanel',
  '\u201CIn the midst of movement and chaos, keep stillness inside of you.\u201D \u2014 Deepak Chopra',
  '\u201CThe things you are passionate about are not random. They are your calling.\u201D \u2014 Fabienne Fredrickson',
  '\u201CStillness is where creativity and solutions to problems are found.\u201D \u2014 Eckhart Tolle',
  '\u201CLess is more.\u201D \u2014 Ludwig Mies van der Rohe',
  '\u201CThe soul usually knows what to do to heal itself. The challenge is to silence the mind.\u201D \u2014 Caroline Myss',
  '\u201COrder is the shape upon which beauty depends.\u201D \u2014 Pearl S. Buck',
  '\u201CTo be calm is the highest achievement of the self.\u201D \u2014 Zen Proverb',
  '\u201CThe unexamined life is not worth living.\u201D \u2014 Socrates',
  '\u201CHe who is contented is rich.\u201D \u2014 Lao Tzu',
  '\u201CSilence is the language of God.\u201D \u2014 Rumi',
  '\u201CThe quieter you become, the more you can hear.\u201D \u2014 Ram Dass',
  '\u201CDo not let the behavior of others destroy your inner peace.\u201D \u2014 Dalai Lama',
  '\u201CEverything you need is already inside you.\u201D \u2014 Th\u00EDch Nh\u1EA5t H\u1EA1nh',
  '\u201CThe greatest weapon against stress is our ability to choose one thought over another.\u201D \u2014 William James',
  '\u201CA cluttered mind is a cluttered life.\u201D \u2014 Unknown',
  '\u201CTrue simplicity is when the inner and outer are aligned.\u201D \u2014 Eckhart Tolle',
  '\u201CLet go of the need to control. Trust the process.\u201D \u2014 Unknown',
];

export function pickRandomPrompt(prompts: readonly string[]): string {
  return prompts[Math.floor(Math.random() * prompts.length)] ?? '';
}
