import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { execSync } from 'node:child_process';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const rootPkgPath = join(__dirname, '../package.json');
const outputPath = join(__dirname, '../apps/frontend/src/app/core/constants/version.ts');

try {
  // 0. Ensure directory exists
  mkdirSync(dirname(outputPath), { recursive: true });

  // 1. Read version from root package.json
  const pkg = JSON.parse(readFileSync(rootPkgPath, 'utf-8'));
  const version = pkg.version || '0.0.0';

  // 2. Validate SemVer
  if (!/^\d+\.\d+\.\d+(-[a-zA-Z0-9.]+)?(\+[a-zA-Z0-9.]+)?$/.test(version)) {
    throw new Error(`Invalid SemVer in package.json: ${version}`);
  }

  // 3. Get Git Metadata
  let hash = 'unknown';
  let branch = 'unknown';
  let tag = 'unknown';

  try {
    hash = execSync('git rev-parse --short HEAD', { stdio: ['ignore', 'pipe', 'ignore'] })
      .toString()
      .trim();
    branch = execSync('git rev-parse --abbrev-ref HEAD', { stdio: ['ignore', 'pipe', 'ignore'] })
      .toString()
      .trim();
    try {
      tag = execSync('git describe --tags --exact-match', { stdio: ['ignore', 'pipe', 'ignore'] })
        .toString()
        .trim();
    } catch (tagError) {
      // Not on a tag
    }
  } catch (e) {
    if (process.env.CI) {
      // Fallback for GitHub Actions or generic CI
      hash = (process.env.GITHUB_SHA || '').substring(0, 7) || 'unknown';
      branch = process.env.GITHUB_REF_NAME || 'unknown';
      if (process.env.GITHUB_REF_TYPE === 'tag') {
        tag = process.env.GITHUB_REF_NAME;
      }

      if (hash === 'unknown' || branch === 'unknown') {
        throw new Error(
          'Critical: Could not retrieve Git metadata in CI via git or env vars (GITHUB_SHA/GITHUB_REF_NAME). Traceability is required for CI builds.',
        );
      }
      console.warn('⚠️ Git commands failed; fell back to CI environment variables for metadata.');
    } else {
      console.warn('⚠️ Could not get Git metadata, defaulting to "unknown"');
    }
  }

  const isDetached = branch === 'HEAD';
  const branchDisplay = isDetached ? `detached@${hash}` : branch;

  // 4. Metadata
  const buildTimestamp = new Date().toISOString();
  const nodeEnv = process.env.NODE_ENV || 'development';

  // 5. Generate content
  const content = `// This file is auto-generated by scripts/generate-version.mjs
export const APP_VERSION = {
  version: ${JSON.stringify(version)},
  tag: ${JSON.stringify(tag)},
  hash: ${JSON.stringify(hash)},
  branch: ${JSON.stringify(branch)},
  isDetached: ${isDetached},
  nodeEnv: ${JSON.stringify(nodeEnv)},
  buildDate: ${JSON.stringify(buildTimestamp)},
  full: ${JSON.stringify(`v${version}+${hash}`)},
} as const;
`;

  // 6. Write to file
  writeFileSync(outputPath, content, 'utf-8');
  console.log(`✅ Version generated: v${version}+${hash} (${branchDisplay}) [${nodeEnv}]`);
} catch (error) {
  console.error('❌ Failed to generate version file:', error.message);
  process.exit(1);
}
